### ISSUE TITLE
#6# 第六章源码缺省

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#10]
posted by @ter123 at http://www.eoeandroid.com/thread-279997-2-19.html

> 其实我第六章的  activity 小实例就没有弄通    可没得源码   手敲上去还不晓得错在哪里了

@river 把你代码pull下。

**Comment by vincent4j** [comment]
@riverfeng

**Comment by IceskYsl** [comment]
@riverfeng 来接客～

**Comment by vincent4j** [comment]
已经 push 上来了，close。
