### ISSUE TITLE
全书错别字集锦

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#12]
from http://my.eoe.cn/893379 at http://www.eoeandroid.com/forum.php?mod=redirect&goto=findpost&ptid=279961&pid=2807837&fromuid=95257

> 159页，12.4.7节代码注释中“表示从数据表mytable的字段_id=1的哪一行开始”应该是“那一行”吧

第12章，159页，12.4.7节，倒数第2行 issue12,1f
现状：//表示从数据库表mytable的字段_id=1的哪
改成：//表示从数据库表mytable的字段_id=1的那
修改：『哪』>『那』

**Comment by vincent4j** [comment]
http://www.eoeandroid.com/forum.php?mod=redirect&goto=findpost&ptid=279961&pid=2813063&fromuid=95257

> 184页，saveTitlePref()中“SharedPreference.Editorprefs”中间少一个空格。
> 同一页，loadTitlePref()中“SharedPreferenceprefs”中间少一个空格。
- 第13章，184页，代码中缺少空格  issue12,2f  
  - 第11行，缺少空格  
    现状：`AppWidgetManagerappWidgetManager = AppWidgetManager.getInstance(context);`  
    改成：`AppWidgetManager appWidgetManager = AppWidgetManager.getInstance(context);`  
    修改：`AppWidgetManagerappWidgetManager` > `AppWidgetManager appWidgetManager`（加个空格）  
  - 第19行，缺少空格  
    现状：`saveTitlePref(intappWidgetId, String text) {`  
    改成：`saveTitlePref(int appWidgetId, String text) {`  
    修改：`intappWidgetId` > `int appWidgetId`（加个空格）  
  - 第20行，缺少空格  
    现状：`SharedPreferences.Editorprefs = getSharedPreferences(PREFS_NAME, 0).edit();`  
    改成：`SharedPreferences.Editor prefs = getSharedPreferences(PREFS_NAME, 0).edit();`  
    修改：`SharedPreferences.Editorprefs` > `SharedPreferences.Editor prefs`（加个空格） 
  - 第26行，缺少空格  
    现状：`loadTitlePref(intappWidgetId) {`  
    改成：`loadTitlePref(int appWidgetId) {`  
    修改：`intappWidgetId` > `int appWidgetId`（加个空格） 
  - 第27行，缺少空格  
    现状：`SharedPreferencesprefs = getSharedPreferences(PREFS_NAME, 0);`  
    改成：`SharedPreferences prefs = getSharedPreferences(PREFS_NAME, 0);`  
    修改：`SharedPreferencesprefs` > `SharedPreferences prefs`（加个空格）

**Comment by vincent4j** [comment]
http://www.eoeandroid.com/forum.php?mod=redirect&goto=findpost&ptid=279961&pid=2818971&fromuid=95257

> 109页   info=info+"/n联系电话"+text.getText();==>String  info=info+"/n联系电话"+text.getText()
> 》这个不是问题 @4j 2013.07.07

110页   10.2.2上面第11行的“利旧”  是不是打印问题？

111页   GridItem.xml 14行   android：layout_below="@+id/ItemImage"==>android：layout_below="@id/ItemImage"

176页    第三段 我们在com.example.widget与程序中的包不一致==》com.eoeandroid.widget

178页    第一个“注意”下面段落第二行 “建议不要更新太频率”==》“建议不要更新太频  繁”

180页 “onUpdate（）”下第二段  “如果想通过手动触发Widget的此函数”里面的“此”不知道读者别扭不别扭

188页 13.5Widget实例上面   minHeight=70-1-30=40dip
==》minHeight=70x1-30=40dip

203页  倒数第二行  “若服务器长时间无法受到客户端的请求”==》“若服务器长时间无法  收  到客户端的请求”

**Comment by vincent4j** [comment]
http://www.eoeandroid.com/forum.php?mod=redirect&goto=findpost&ptid=279961&pid=2823943&fromuid=95257

> 第十五章    开篇倒数第二行   “UI界面都不会直接实用View”==》”UI界面都不会直接  使  用View“
> 236页  4.不同的网络连接模式使用不同的下载模式    第三行   “在大多数情况下使用用”==》多了个”用“

**Comment by krislq** [comment]
《android开发入门与实践第二版》第110页第八段"旧并"是错别字吧？
反馈连接：http://weibo.com/2709568713/zAcq2plik#_rnd1370585655448

另外 : 那一段还有 "利旧" 也是打错了的

**Comment by krislq** [comment]
啥也不说了，写在EoE的。。太不专业了。
![img_20130608_084255](https://f.cloud.github.com/assets/861095/626839/bca05f4c-cfd4-11e2-94ef-d90612bc53df.jpg)

**Comment by vincent4j** [comment]
我也年轻过，有个问题，projectname咋取？Helloeoe？别扭不？

在 2013年6月8日星期六，Kris.lee 写道：

> 啥也不说了，写在EoE的。。太不专业了。
> [image: img_20130608_084255]https://f.cloud.github.com/assets/861095/626839/bca05f4c-cfd4-11e2-94ef-d90612bc53df.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/google_android_book_v2/issues/12#issuecomment-19140143
> .

## 

Best Regards;
Vincent 4J http://about.me/vincent4j

**Comment by krislq** [comment]
一般是首字母大写嘛。
特殊情况 ：
1.像一些缩写，比如 ET , UFO 这种，不管在哪里都大写的，用在项目名时也应该大写。
2.对于一些有特殊规定或者是意义的，就按官方的大小写来定吧。比如 eoe官方规定全是小写，那不管在哪里都应该是小写。

所以在这里我觉得Helloeoe更好点。其实直接  HelloWorld多好啊，非得加上个eoe在里面。嘿嘿。。。

@IceskYsl  觉得呢？

**Comment by IceskYsl** [comment]
HelloMyeoe 

:+1:

**Comment by krislq** [comment]
来至: http://weibo.com/1897430884/zAKrnzrAc
![http://ww2.sinaimg.cn/bmiddle/71187f64jw1e5itd0sg5fj20xc18gtfs.jpg](http://ww2.sinaimg.cn/bmiddle/71187f64jw1e5itd0sg5fj20xc18gtfs.jpg)

**Comment by krislq** [comment]
刚看到第六章，有两个小错误，语句不通顺直接上照片，图中用铅笔画线的地方就是我感觉不通顺的地方
来至:http://weibo.com/1897430884/zAKqC0YX5
![](http://ww2.sinaimg.cn/bmiddle/71187f64jw1e5itb1bhczj20xc18gaj0.jpg)

**Comment by vincent4j** [comment]
手机终于有信号咯

在 2013年6月10日星期一，Kris.lee 写道：

> 刚看到第六章，有两个小错误，语句不通顺直接上照片，图中用铅笔画线的地方就是我感觉不通顺的地方
> 来至:http://weibo.com/1897430884/zAKqC0YX5
> 
> https://a248.e.akamai.net/camo.github.com/5e3d36a1b4227bb550ff83b2c1d030b1aa250b92/687474703a2f2f7777322e73696e61696d672e636e2f626d6964646c652f37313138376636346a77316535697462316268637a6a32307863313867616a302e6a7067
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/google_android_book_v2/issues/12#issuecomment-19178919
> .

## 

Best Regards;
Vincent 4J http://about.me/vincent4j

**Comment by krislq** [comment]
《Android开发入门与实战（第二版）》勘误：第68页 第15行 new Intent（HelloWorldActivity.this,ActivityC.class） 应为 new Intent（HelloWorldActivity.this,ActivityB.class）

来自:http://weibo.com/1710084123/zBvcp9eHu

**Comment by krislq** [comment]
第53页倒数第6行：“ldpi放置中等分辨率图片”是错误的

refer to : http://weibo.com/3211268602/zBA2wfUGq
@企业搜索引擎_微软

**Comment by vincent4j** [comment]
第213页，倒数第2行
现在是：不会直接实用 View 和 ViewGroup.
不是『实用』，应该是『使用』。

ref：http://weibo.com/1651809125/zEk501E3X

**Comment by vincent4j** [comment]
第19章，258页，第3行 issue#12  
现状：`（1）启动第三方应用“Zxing”对图书条形码进行扫描，进而得到条形码`  
改成：`（1）启动第三方应用“ZXing”对图书条形码进行扫描，进而得到条形码`  
修改：`Zxing` > `ZXing`

**Comment by krislq** [comment]
178页 第一个“注意”下面段落第二行 “建议不要更新太频率”==》“建议不要更新太频 繁”
》》建议不要更新太频繁

**Comment by krislq** [comment]
176页 第三段 我们在com.example.widget与程序中的包不一致==》com.eoeandroid.widget
》然后，我们在com.eoeandroid.widget包下新建一个名为

**Comment by krislq** [comment]
180页 “onUpdate（）”下第二段 “如果想通过手动触发Widget的此函数”里面的“此”不知道读者别扭不别扭
》不需要修改，在这里此字代表onUpdate()方法

**Comment by vincent4j** [comment]
下面 3 处修改都已经摘录至 wiki：  @krislq 
178页 第一个“注意”下面段落第二行 “建议不要更新太频率”==》“建议不要更新太频 繁”
》》建议不要更新太频繁

176页 第三段 我们在com.example.widget与程序中的包不一致==》com.eoeandroid.widget
》然后，我们在com.eoeandroid.widget包下新建一个名为

180页 “onUpdate（）”下第二段 “如果想通过手动触发Widget的此函数”里面的“此”不知道读者别扭不别扭
》不需要修改，在这里此字代表onUpdate()方法

**Comment by krislq** [comment]
@vincent4j  帅气 。

**Comment by krislq** [comment]
188页 13.5Widget实例上面 minHeight=70-1-30=40dip
==》minHeight=70x1-30=40dip @vincent4j

**Comment by vincent4j** [comment]
下面一条已经收录进 wiki：
188页 13.5Widget实例上面 minHeight=70-1-30=40dip
==》minHeight=70x1-30=40dip

**Comment by vincent4j** [comment]
eoe 大小写的问题，刚 new issue，全部迁移过去了：  #30

**Comment by IceskYsl** [comment]
√
