### ISSUE TITLE
封底有个作者的介绍印少了一句很重要的话，如果加印必须加上~

### ISSUE THREAD

**Issue by IceskYsl** [eoecn/google_android_book_v2#13]
刘彦杰(@huaxiannv)　的加上这句
特别感谢:王维(著名Android开发工程师)

郝留有(@haoliuyou)
去掉这句：eoeAndroid社区管理员,

**Comment by vincent4j** [comment]
金建刚 (@hexer)  改为：金建刚 (@hexter)

**Comment by IceskYsl** [comment]
擦~果然错了〜　罪过罪过〜

**Comment by vincent4j** [comment]
能把小钢帽也换个素描吗？真是不协调。
