### ISSUE TITLE
第6页～日期的错误，2010 12 06 Android 2.3 SDK 发表。 是印刷错误？

### ISSUE THREAD

**Issue by krislq** [eoecn/google_android_book_v2#15]
来源：http://weibo.com/1852208005/zAkoKeYNB

第6页～日期的错误，2010 12 06 Android 2.3 SDK 发表。 是印刷错误？

时间错了

**Comment by vincent4j** [comment]
@IceskYsl 这个啥意思啊，说时间写错啦？刚查了下，木写错啊，就是2010.12.06啊？

**Comment by IceskYsl** [comment]
看那个图，时间不是顺序的
http://ww4.sinaimg.cn/bmiddle/6e667385jw1e5fm9vmv8lj20xc18gjx9.jpg

**Comment by vincent4j** [comment]
已经收录：
https://github.com/eoecn/google_android_book_v2/wiki/%E7%AC%AC1%E6%AC%A1%E5%8D%B0%E5%88%B7%E9%97%AE%E9%A2%98%E7%BB%9F%E8%AE%A1

log：第1章，6页，sdk 发布未按照时间升序排列 issue#15 [5f2c2b6]

**Comment by vincent4j** [comment]
已经摘录，可以 colse 掉。
