### ISSUE TITLE
#前言# 源程序下载网址错误

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#16]
第6页，网址写成第一版的了：
由
http://www.eoeandroid.com/group-35-1.html
改成
http://www.eoeandroid.com/group-812-1.html

**Comment by IceskYsl** [comment]
接受〜

**Comment by vincent4j** [comment]
http://www.eoeandroid.com/forum-35-1.html

换成这个地址吗？ @IceskYsl  确认下？

**Comment by IceskYsl** [comment]
是这个，好像还有一个地方有网址。
在 2013-7-7 下午10:45，"Vincent 4J" notifications@github.com写道：

**Comment by vincent4j** [comment]
封底的扉页
