### ISSUE TITLE
#10# weight权重的反馈

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#20]
from @snowxwyo

@人民邮电出版社-信息技术分社 @eoe移动开发者社区 weight权重的问题我试验的结果为什么和书上说的相反呢？我得出的结果是weight越大权重越大呀

ref: http://weibo.com/1897430884/zBnEciB89

**Comment by krislq** [comment]
![weight](https://f.cloud.github.com/assets/861095/652715/e6da85b8-d4ba-11e2-856d-f028666ab5a4.png)

代码如下：

``` java
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context=".MainActivity" >
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <TextView
            android:id="@+id/textView1"
            android:layout_weight="0.5"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="Weight 0.5"
            android:background="#ff0" />

        <TextView
            android:id="@+id/textView2"
            android:layout_weight="1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="Weight 1"
            android:background="#f00"/>
    </LinearLayout>

</RelativeLayout>
```

**Comment by snowxwyo** [comment]
kris大神这个设的有问题，官方文档说了，weight的时候，要么width为零，要么height为零，这种情况下数值越大，权重越大，官方文档是这么写的

发自我的 iPhone

在 2013-6-14，14:23，"Kris.lee" notifications@github.com 写道：

**Comment by krislq** [comment]
@snowxwyo  你是相信眼见为实还是文档 ？ 或者你把你的实际效果帖出来征服我

**Comment by vincent4j** [comment]
他手机，可能不方便吧。再有文档，贴具体的链接。

**Comment by futurexiong** [comment]
哈哈，weight这个属性比较复杂，两种结果都有可能的，要看布局如何去写。

**Comment by krislq** [comment]
@futurexiong 哦？哪种情况下可以实现weight值越大占的比重越大？

**Comment by futurexiong** [comment]
最简单的就是width或者height为0嘛

futurexiong

**Comment by snowxwyo** [comment]
width或height其中一项设置为0dp的时候，weight越大，权重越大，我试过了，但现在没网，只能用手机，发不了截图

发自我的 iPhone

在 2013-6-14，15:03，"Kris.lee" notifications@github.com 写道：

**Comment by krislq** [comment]
@snowxwyo  @futurexiong @vincent4j 
总结下： (前提是horizontal->width ; vertical ->height)
1.width或height其中一项设置为0dp的时候，weight越大，权重越大
2.width或height其中一项设置为match_parent的时候，weight越大，权重越小
3.width或height其中一项设置为wrap_content的时候，自动适应

**Comment by vincent4j** [comment]
已经摘录进 wiki，可以 close 掉。
