### ISSUE TITLE
#8# 第86页：onStart() ? onStartCommand()

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#21]
> 《Android开发入门与实战》第86页，HelloService的onStart方法，不是不写错了，应该是onStartCommand方法？

ref： http://www.weibo.com/1890903115/zCgOr8zh2

**Comment by vincent4j** [comment]
在1.6或1.6之前，只有Service.onStart()方法。等到2.0时，Service.onStartCommand()出现，同时Service.onStart()不推荐使用。

毕竟当前1.6机器几乎已经绝迹，所以这也是作者的一个疏忽，应该使用官方推荐的 onStartCommand，而不是 onStart（虽说onStart也不会有错）。期待在下次印刷中修正；同时，多谢 http://weibo.com/darkeeeeeeeer 的反馈。

官方文档：
http://developer.android.com/guide/components/services.html#CreatingStartedService

http://developer.android.com/reference/android/app/Service.html#onStartCommand(android.content.Intent, int, int)

![issue1](https://f.cloud.github.com/assets/808989/679058/71432c04-d953-11e2-8aea-6d48f888600d.png)

**Comment by jackspec** [comment]
回复有很效率

**Comment by vincent4j** [comment]
既然该问题得到回复，那我就close掉了。@jackspec
