### ISSUE TITLE
#12# 12.3源码问题：java.lang.NoClassDefFoundError: com.db4o.Db4oEmbedded

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#22]
06-24 14:41:47.294: E/AndroidRuntime(20367): FATAL EXCEPTION: main
06-24 14:41:47.294: E/AndroidRuntime(20367): java.lang.NoClassDefFoundError: com.db4o.Db4oEmbedded
06-24 14:41:47.294: E/AndroidRuntime(20367):         at com.lyj.cn.main.onCreate(main.java:19)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.Activity.performCreate(Activity.java:4470)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1052)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.ActivityThread.access$600(ActivityThread.java:127)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.os.Handler.dispatchMessage(Handler.java:99)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.os.Looper.loop(Looper.java:137)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at android.app.ActivityThread.main(ActivityThread.java:4511)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at java.lang.reflect.Method.invokeNative(Native Method)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at java.lang.reflect.Method.invoke(Method.java:511)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
06-24 14:41:47.294: E/AndroidRuntime(20367):         at dalvik.system.NativeStart.main(Native Method)

ref: http://www.eoeandroid.com/thread-288127-1-1.html

**Comment by liuyiyi11** [comment]
源码没有问题，我跟提出问题的读者认真沟通过，是读者的开发环境设置问题，源码完全正确，无需修改。

**Comment by vincent4j** [comment]
了然 @liuyiyi11

**Comment by IceskYsl** [comment]
那就先close掉啦〜
