### ISSUE TITLE
#15# 214页，不理解：框架将不会画不在失效区域的视图

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#24]
第三段倒数第2行，有童鞋反馈下面的话不理解：

> 框架将不会画不在失效区域的视图

请作者 @haoliuyou 帮忙解释下。

ref：http://weibo.com/1651809125/zEk501E3X

**Comment by IceskYsl** [comment]
框架会重画失效区域的视图

**Comment by vincent4j** [comment]
from 该章作者：
现状：框架将不会画不在失效区域的视图，而且还会帮你画视图背景。
改成：对于不在失效区域内的视图，Android 绘制框架不会重绘该部分的视图，但是会重绘视图背景。

**Comment by vincent4j** [comment]
已经摘录进 wiki，close 先。
