### ISSUE TITLE
第1次印刷问题统计

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#25]
https://github.com/eoecn/google_android_book_v2/wiki/%E7%AC%AC1%E6%AC%A1%E5%8D%B0%E5%88%B7%E9%97%AE%E9%A2%98%E7%BB%9F%E8%AE%A1

https://github.com/eoecn/google_android_book_v2/wiki/%E7%AC%AC1%E6%AC%A1%E5%8D%B0%E5%88%B7%E9%97%AE%E9%A2%98%E7%BB%9F%E8%AE%A1(%E5%BE%85%E5%AE%9A)

最初打算我一一核对，能修复的就帮忙修复掉；结果做到一半，实在是工作量太大了，一个人时间不够用；所以还是按照以下方案：
1. 4j只负责统计，包括问题核实；但不去给出修改方案；
2. 待4j统计完成之后，通过大家；大家将各自的文章修正，即给出修改方案；
3. 4j再行统计，最终给出第2版本的修改方案。

具体的修改方案的格式，大家可以参照上面2个链接中的内容。

好啦，今天统计到 #12 ，有点事先出去了，晚上接着做。

**Comment by IceskYsl** [comment]
工作量好大～

**Comment by vincent4j** [comment]
好啦，统计完成了，将之前的2个wiki整合成一个了，1楼中的链接就不要看了，直接看下面的：
https://github.com/eoecn/google_android_book_v2/wiki/%E7%AC%AC1%E6%AC%A1%E5%8D%B0%E5%88%B7%E9%97%AE%E9%A2%98%E7%BB%9F%E8%AE%A1

作者们现在需要做的事情：
1. 打开上面的wiki，由上往下查看每个问题，遇到自己章节的问题，并且还未解决的；
2. 打开对应的issue，并将解决方案贴在对应issue最下面；
3. 直到自己的所有问题都解决。
4. 在 #25 下跟贴，将自己所有给出解决方案的issue id都贴上来。

4j稍后会根据大家的方案，去跟新统计wiki。

**Comment by liuyiyi11** [comment]
https://github.com/eoecn/google_android_book_v2/issues/22

**Comment by IceskYsl** [comment]
封面扉页修改下介绍&书中赠送一个eoe极客学院的优惠码
这2个到时编辑找我沟通就可以了~

**Comment by IceskYsl** [comment]
各位作者尽快跟进自己的章节～ 这2天这个要汇总完成给出版社开始排版，马上要加印了～

**Comment by vincent4j** [comment]
家伙们都木watch，他们还是习惯qq，效率阿。

在 2013年7月9日星期二，IceskYsl 写道：

> 各位作者尽快跟进自己的章节～ 这2天这个要汇总完成给出版社开始排版，马上要加印了～
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/google_android_book_v2/issues/25#issuecomment-20643027
> .

## 

Best Regards;
Vincent 4J http://about.me/vincent4j

**Comment by vincent4j** [comment]
以下几个问题都已经统计完毕：  
@liuyiyi11  #22

@IceskYsl   

> 封面扉页修改下介绍&书中赠送一个eoe极客学院的优惠码
> 这2个到时编辑找我沟通就可以了~

@vincent4j #2   #12 17f   #19  #26

**Comment by vincent4j** [comment]
已经收录： #15

**Comment by vincent4j** [comment]
@krislq 你的 13 20 章问题都已经全部修复，你解放咯。

**Comment by krislq** [comment]
@vincent4j  yeah !!! 坐等第二版出书。
坐等第一版稿费。。。

**Comment by IceskYsl** [comment]
@krislq 收到请求，我去催催出版社～
