### ISSUE TITLE
hexter 修改

### ISSUE THREAD

**Issue by hexter** [eoecn/google_android_book_v2#28]
第10章，111页，Griditem.xml代码块中，第14行。 issue12,3f
现状：android:layout_below="@+id/ItemImage"
修改成： android:layout_below="@id/ItemImage"

第10章，104页，倒数第4段，倒数第1行：关于 layout_weight issue#20
现状：(layout_weight越小权重越大)
修改成：（width或height设置为0dp的时候，weight越大，权重越大；width或height设置为match_parent的时候，weight越大，权重越小）

第10章，110页，利旧 issue#12,3f 

第7段，倒数第2行： convertView是可以利旧的view，
修改：  convertView是可以回收利用的view
第8段，第1行： 第53行和第64行的if(convertView == null)就是为了利旧
修改：利旧 > 利用旧的view
第8段，第2行： 如果convertView存在直接利旧并把convertView里
修改：如果convertView存在就直接利用，并把convertView里

第10章，110页，第8段，第2行 issue#12,5f
现状：如果convertView存在直接利旧并把convertView里的
问题：如果convertView存在就直接利用，并把convertView里

第10章，第111-112页 Griditem.xml这段13行 issue#14
现状：android:id="@+id/ItemText"
改成：android:id="@+id/itemTitle"

**Comment by vincent4j** [comment]
copy

**Comment by vincent4j** [comment]
第7段，倒数第2行： convertView是可以利旧的view，
修改： convertView是可以利用的旧view

> > ?读都读不通过

**Comment by vincent4j** [comment]
第8段，第1行： 第53行和第64行的if(convertView == null)就是为了利旧
修改：利旧 > 利用旧的view

> 原文是最后是 itemview，要改成 view？/？？？

**Comment by hexter** [comment]
第7段，倒数第2行： convertView是可以利旧的view，
修改： convertView是系统回收利用的view

第8段，第1行： 第53行和第64行的if(convertView == null)就是为了利旧
修改：利旧 > 回收利用作废的view

**Comment by vincent4j** [comment]
@hexter copy，好啦，就它了。

**Comment by vincent4j** [comment]
已经摘录进wiki：
https://github.com/eoecn/google_android_book_v2/wiki/%E7%AC%AC1%E6%AC%A1%E5%8D%B0%E5%88%B7%E9%97%AE%E9%A2%98%E7%BB%9F%E8%AE%A1/c7ed23744c80fa44d0213b2264a261b9dc54ef45

**Comment by IceskYsl** [comment]
√

**Comment by vincent4j** [comment]
可以 close 咯 @IceskYsl

**Comment by IceskYsl** [comment]
√
