### ISSUE TITLE
#13# 代码排版问题：部分代码左对齐

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#29]
在13章中，java 代码的排版都是没问题的；但部分 xml 的排版采用了左对齐；页码罗列如下：
- 176页，widget.xml
- 177页，provider.xml
- 178页，AndroidMainfest.xml
- 185页，provider.xml
- 187页，res/values/dimens.xml
- 196页，res/values/dimens.xml

**Comment by vincent4j** [comment]
@krislq 出来接客咯

**Comment by krislq** [comment]
@vincent4j 收到啰。。。。

**Comment by krislq** [comment]
已经修改完了 D:\Dropbox\eoeBooks\01.入门与实战（第二版）\06_排版后\排版后的书稿(13.07.15)\13.doc
@vincent4j 等会儿帮我 check 一下，ok后close掉本issue哈

**Comment by vincent4j** [comment]
自己的章节还是自己去校准，俺也木那么多时间，也不能让你们养成偷懒的习惯。  @krislq

**Comment by IceskYsl** [comment]
搞定和我说下，我让编辑用最新的~

**Comment by krislq** [comment]
D:\Dropbox\eoeBooks\01.入门与实战（第二版）\06_排版后\排版后的书稿(13.07.15)\13-fixed.DOC

**Comment by krislq** [comment]
@vincent4j  @IceskYsl  快来围观下。你们关一下，我好像不能关。
