### ISSUE TITLE
规则：如何直接在 Dropbox 上的 doc 文档上进行纠错

### ISSUE THREAD

**Issue by vincent4j** [eoecn/google_android_book_v2#37]
## 文档路径

Dropbox\eoeBooks\01.入门与实战（第二版）\06_排版后\排版后的书稿(13.07.15)   
## 注意事项

不要直接在原始文档上修改，不去动原始文档；而是复制出一份，在新复制的文档上进行修改。

例如，kris 想要修改『13.DOC』，首先复制并另存为『13-fixed.DOC』；然后在『13-fixed.DOC』上进行修改，而不去动『13.DOC』。

还有一点很重要，自己本地一定要离线存储一份，在线的东西总是存在安全隐患，例如：被别人不小心覆盖掉（虽说 Dropbox 有版本控制）。
## 规则

修改的宗旨：一定要第三者一看就立马能明白，你是从神马修改成神马。例如：代码缩进的问题，程序员应该很清楚；但编辑们并非专业出生，他们肯定是你作者给我么我就显示么；因为他们压根不懂，所以也不可能提示疑惑。

采用『批注』的形式，具体参看 kris 的第 13 章：
Dropbox\eoeBooks\01.入门与实战（第二版）\06_排版后\排版后的书稿(13.07.15)\13-fixed.DOC

**Comment by IceskYsl** [comment]
√
