### ISSUE TITLE
#20# eoeWiKI源码还是运行不了？

### ISSUE THREAD

**Issue by xiaolai913** [eoecn/google_android_book_v2#39]
运行错误如下：
![bug1](https://f.cloud.github.com/assets/1133559/906595/8ab237d6-fcba-11e2-996c-8bbfff0d7268.png)

**Comment by IceskYsl** [comment]
那个地址又访问不了了？

**Comment by krislq** [comment]
@IceskYsl  不是那个的问题哦。。是他的第三库没找到。蛋疼。。

**Comment by vincent4j** [comment]
那你 url 为嘛要用 error 打出来。

**Comment by krislq** [comment]
debug=true 就会把所有信息打印出来啊。。
与下面报错没半毛钱关系啊。。。

**Comment by krislq** [comment]
@xiaolai913  从错误 来看是因为 umeng的第三方库没有加载成功。
你看看你的项目里面有没有把所有的 jar都导入。如果 都导入了，
再看看properties->java build >order and export里面的勾都打上呢？
再clean一下项目。

**Comment by IceskYsl** [comment]
楼上正解~

**Comment by xiaolai913** [comment]
@krislq @IceskYsl @vincent4j 谢谢各位！问题解决了，原来是路径中带了中文，导致第三方库木有找到~

**Comment by vincent4j** [comment]
@xiaolai913   copy that. 麻烦你把该 issue close下。
