### ISSUE TITLE
12章notepad的源码是不是有问题？

### ISSUE THREAD

**Issue by drinktee** [eoecn/google_android_book_v2#42]
进入查看内容页面后，连续不能连续删除两个item???

**Comment by vincent4j** [comment]
收到，明天找作者给你答复

drinktee notifications@github.com于2014年5月18日星期日写道：

> 进入查看内容页面后，连续不能连续删除两个item???
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eoecn/google_android_book_v2/issues/42
> .

## 

Best Regards,
Vincent 4J http://about.me/vincent4j.

**Comment by liuyiyi11** [comment]
亲爱的读者，您好！
关于您提出的问题，我认真的研究和分析了一下。
1、不可以连续点击，连续删除的。因为：只有选中一项，才能删除一项。毕竟这里是单项删除。如果界面列表中的其它项（item），在没有选中的情况下，因为连续点击了对话框中的“删除项”，界面列表中的其它项就被删除了，这样子的话，程序的这个设计就算是bug了。
2、关于在对话框中的“删除项”中重新实例化一个cursor，是为了在点击了“删除项”以后，立马让处于对话框底部的界面中的列表改变立马显示出来。试想，如果用户点击了对话框中的某个改变界面的选项，界面的变化竟然没有立马体现出来，这样的体验是很糟糕的。
因此，源码整体是没有错误的。不过读者可以继续研究探讨优化。
以上是我的个人观点，仅供参考。如有不妥之处，可以继续探讨。谢谢。
