### ISSUE TITLE
#13#RecentService 多余

### ISSUE THREAD

**Issue by krislq** [eoecn/google_android_book_v2#6]
``` java
<application android:label="@string/app_name"
        android:icon="@drawable/icon"
        android:theme="@style/AppTheme">
        <receiver android:name=".WikiRecent">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
            </intent-filter>
            <meta-data android:name="android.appwidget.provider" android:resource="@xml/widget_provider" />
        </receiver>
        <service android:name=".RecentService" />
    </application>
```

<service android:name=".RecentService" /> 多余

**Comment by krislq** [comment]
refer to this pull request:
[click to view this pull request](https://github.com/eoecn/google_android_book_v2/pull/7)

**Comment by krislq** [comment]
又打开干嘛？

**Comment by IceskYsl** [comment]
因为4j说等下一版都修复过来了再close

**Comment by krislq** [comment]
@vincent4j  看这里。。。
https://github.com/krislq/google_android_book_v2/commit/b48439f57378d7570bfaef8be635e53f5cede72e

**Comment by vincent4j** [comment]
第13章，196页， `AndroidManifest.xml` 代码块，倒数第4行  issue#6
问题：Service 声明多余。
删除：`<service android:name=".RecentService" />` 这一整行。

**Comment by vincent4j** [comment]
已经摘录进 wiki

**Comment by krislq** [comment]
@vincent4j 正确。帅气 。上档次 。谢谢4j .来四川，请你吃火锅
